### ISSUE TITLE
error about pretrained model

### ISSUE THREAD

**Issue by Jingchensun** [ooooverflow/BiSeNet#21]
when i use the model epoch_295.pth in GoogleDrive and put it in ./checkpoints ,run eval.py, it comes a error like this: 

load model from /root/data/Seg_Pytorch/BiSeNet-master/checkpoints/epoch_295.pth ...
Traceback (most recent call last):
  File "eval.py", line 97, in <module>
    main(params)
  File "eval.py", line 82, in main
    model.module.load_state_dict(torch.load(args.checkpoint_path))
  File "/root/miniconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BiSeNet:
	Missing key(s) in state_dict: "supervision1.weight", "supervision1.bias", "supervision2.weight", "supervision2.bias". 
	Unexpected key(s) in state_dict: "saptial_path.convblock1.bn.num_batches_tracked", "saptial_path.convblock2.bn.num_batches_tracked", "saptial_path.convblock3.bn.num_batches_tracked", "context_path.features.bn1.num_batches_tracked", "context_path.features.layer1.0.bn1.num_batches_tracked", "context_path.features.layer1.0.bn2.num_batches_tracked", "context_path.features.layer1.0.bn3.num_batches_tracked", "context_path.features.layer1.0.downsample.1.num_batches_tracked",

You said the net structure has been modified, so the pretrained model does not match the current model, so do you have any other pre-trained mode recommend for this network?

**Comment by ooooverflow** [comment]
I may update another pre-trained model in a few days if i get a free time, sorry
