### ISSUE TITLE
The performance on CityScape dataset

### ISSUE THREAD

**Issue by Jingchensun** [ooooverflow/BiSeNet#24]
1.Have you trained your model on CItyscape dataset? When I change the dataset from Camvid to Cityscape, run the train.py, i get an error like this:
`epoch 0, lr 0.001000:   0%|                                                                                        | 0/744 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 206, in <module>
    main(params)
  File "train.py", line 187, in main
    train(args, model, optimizer, dataloader_train, dataloader_val, csv_path)
  File "train.py", line 86, in train
    for i,(data, label) in enumerate(dataloader_train):
  File "/home/sunjingchen/miniconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/sunjingchen/miniconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/sunjingchen/miniconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sunjingchen/miniconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sunjingchen/BiSeNet-City/dataset/CamVid.py", line 81, in __getitem__
    label = one_hot_it(label, self.label_info).astype(np.uint8)
  File "/home/sunjingchen/BiSeNet-City/utils.py", line 44, in one_hot_it
    equality = np.equal(label, color)
ValueError: operands could not be broadcast together with shapes (640,640,4) (3,)`

Could you tell me what's the reason of this error?  I think maybe is the format of Camvid dataset is different from Cityscape dataset.

2.Have you tested the speed of BiSeNet on Camvid,  Is it near to105FPS?

Thank you very much!

**Comment by lixhere** [comment]
请问如何测试速度？

**Comment by lixhere** [comment]
May I know how to test speed (fps)？Thank you！
