### ISSUE TITLE
Error: FileNotFoundError: [Errno 2] No such file or directory: '/path/to/ckpt/'

### ISSUE THREAD

**Issue by Hekeshi** [ooooverflow/BiSeNet#29]
BiSeNet$ python demo.py

Traceback (most recent call last):
  File "demo.py", line 81, in <module>
    main(params)
  File "demo.py", line 60, in main
    model.module.load_state_dict(torch.load(args.checkpoint_path))
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/ckpt/'

Could you tell me why this error will happen? How could I solve this problem?

**Comment by KimJA111** [comment]
I have the same problem. Have you solved this?
